version: '3'

#if problem version cant detect version 3 read this https://github.com/bigbluebutton/greenlight/issues/228#issuecomment-545919537
#thanks to : https://medium.com/gdgsrilanka/running-jenkins-on-docker-for-a-newbie-855ad376500b

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    image: blst/jenkinsdocker
    container_name: jenkinsmasterdocker
    restart: unless-stopped
    tty: true
    networks:
      - jenkins
    volumes:
      - jenkinsnewdata:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    ports:
      - "9090:8080"

# Docker Network
networks:
  jenkins:
    driver: bridge

#Volumes
volumes:
  jenkinsnewdata:
    driver: local
