version: '3'

#if problem version cant detect version 3 read this https://github.com/bigbluebutton/greenlight/issues/228#issuecomment-545919537
#thanks to : https://medium.com/gdgsrilanka/running-jenkins-on-docker-for-a-newbie-855ad376500b

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    image: blst/jenkinsdocker
    container_name: jenkinsmasterdocker
    restart: unless-stopped
    tty: true
    environment:
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: 1
    networks:
      - jenkins
    volumes:
      - jenkins-data:/var/jenkins_home
      - /jenkins_volume:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins-docker-certs:/certs/client:ro
    ports:
      - "8080:8080"

# Docker Network
networks:
  jenkins:
    driver: bridge

#Volumes
volumes:
  jenkins-data:
    driver: local
  jenkins-docker-certs:
    driver: local
